project:
  type: website

website:
  title: "Pre-School Workshop: Reproducible Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slide/repro-preschool.html
        text: slide
      - href: example-compendium/index.qmd
        text: Compendium

format:
  html:
    theme: cosmo
    toc: true

